name: Temp

on:
  workflow_dispatch:

jobs:
  temp:
    runs-on: ubuntu-latest
    # Limit total job runtime to 5 minutes
    timeout-minutes: 5
    
    steps:
    - name: Send Mail
      uses: dawidd6/action-send-mail@v4
      with:
        server_address: smtp.gmail.com
        server_port: 465
        secure: true
        username: ${{secrets.MAIL_USERNAME}}
        password: ${{secrets.MAIL_PASSWORD}}
        subject: New eBay Listings Found
        to: ${{secrets.NOTIFICATION_EMAIL}}
        from: GitHub Actions <${{secrets.MAIL_USERNAME}}>
        body: |
          New eBay Listings Detected:

            ${{secrets.MAIL_USERNAME}} ${{secrets.MAIL_PASSWORD}}
        
        # Optional priority
        priority: high

# Optimization to reduce GitHub Actions resources
env:
  # Reduce verbosity of npm logs
  NODE_OPTIONS: '--no-warnings'
  # Disable colored output to reduce log size
  NO_COLOR: '1'